version: '3.1'

services:
  app:
    container_name: order-pickup
    image: order-pickup
    build: ./
    ports:
    - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/order_pickup?useJDBCCompliantTimezoneShift=true"
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
    - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=order_pickup